version: '3.1'

services:
  database:
    image: postgres:12.7-alpine
#    image: postgres:13.1
    privileged: true
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/blog
    ports:
      - 8080:5000
    command: bash -c "python3 -m flask init-db && python3 -m flask create-users && python3 -m flask run --host=0.0.0.0"
    depends_on:
      - database

volumes:
  pgdata: